import { useState } from "react";

import type { NextPage } from "next";
import Head from "next/head";
import { Container, Grid, Typography, Button, Drawer } from "@mui/material";
import { useQueryClient, useQuery, useMutation } from "react-query";

import MaterialForm from "@/components/Materials/MaterialForm";
import MaterialTable from "@/components/Materials/MaterialTable";

import { getMaterials, deleteMaterial } from "api";
import styles from "./styles.module.scss";
import { useRecoilState } from "recoil";
import { editState } from "@/components/Materials/state";

const Materials: NextPage = () => {
  const queryClient = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [editMaterial, setEditMaterial] = useRecoilState(editState);

  const { data: response } = useQuery("materials", getMaterials);
  const materials = response?.data;

  const onChange = () => {
    queryClient.invalidateQueries("materials");
    setShowForm(false);
    setEditMaterial(null);
  };

  // Delete Reservation
  const { mutate: handleDelete } = useMutation(
    (id: number) => {
      return deleteMaterial(id);
    },
    {
      onSuccess: () => {
        queryClient.invalidateQueries(["materials"]);
      },
    }
  );

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Materijali</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Container>
            <Grid
              container
              sx={{ justifyContent: "space-between", mb: 2, mt: 3 }}
            >
              <Grid item>
                <Typography variant="h4">Materijali</Typography>
              </Grid>
              <Grid item>
                <Button variant="contained" onClick={() => setShowForm(true)}>
                  Dodaj materijal
                </Button>
              </Grid>
            </Grid>
            {materials && <MaterialTable materials={materials} />}
          </Container>
        </main>
      </div>

      <Drawer
        anchor="right"
        open={showForm || !!editMaterial}
        classes={{ paper: styles.userDrawer }}
        onClose={() => {
          setShowForm(false);
          setEditMaterial(null);
        }}
      >
        <MaterialForm onChange={onChange} />
      </Drawer>
    </>
  );
};

export default Materials;
